CREATE DATABASE IF NOT EXISTS label_system CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE label_system;

CREATE TABLE IF NOT EXISTS label_templates (
    id VARCHAR(36) PRIMARY KEY COMMENT '模板ID(UUID)',
    name VARCHAR(200) NOT NULL COMMENT '模板名称',
    target_entity VARCHAR(50) NOT NULL DEFAULT 'delivery' COMMENT '目标实体',
    layout_json LONGTEXT NOT NULL COMMENT '完整布局JSON',
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='标签打印模板';
